import web3 from '../web3';

// const contractAccount ="0x5Ee233C6466573a64F410Ac1b8d218959fA18771"
const abi = JSON.parse(
  '[{"inputs":[{"internalType":"address payable","name":"_beneficiary","type":"address"},{"internalType":"uint256","name":"secondsToEnd","type":"uint256"},{"components":[{"internalType":"string","name":"id","type":"string"},{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"image","type":"string"},{"internalType":"string","name":"description","type":"string"}],"internalType":"struct Auction.Lot","name":"_lot","type":"tuple"}],"stateMutability":"nonpayable","type":"constructor","signature":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"winner","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"AuctionEnded","type":"event","signature":"0xdaec4582d5d9595688c8c98545fdd1c696d41c6aeaeb636737e84ed2f5c00eda"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"bidder","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"NewBid","type":"event","signature":"0xdd0b6c6a77960e2066c96171b4d7ac9e8b4c184011f38544afa36a5bb63ec59f"},{"inputs":[],"name":"beneficiary","outputs":[{"internalType":"address payable","name":"","type":"address"}],"stateMutability":"view","type":"function","constant":true,"signature":"0x38af3eed"},{"inputs":[],"name":"endAuction","outputs":[],"stateMutability":"nonpayable","type":"function","signature":"0xfe67a54b"},{"inputs":[],"name":"endTime","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function","constant":true,"signature":"0x3197cbb6"},{"inputs":[],"name":"ended","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function","constant":true,"signature":"0x12fa6feb"},{"inputs":[],"name":"lastBid","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function","constant":true,"signature":"0x5e3d3957"},{"inputs":[],"name":"lastBidder","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function","constant":true,"signature":"0x8547af30"},{"inputs":[],"name":"lot","outputs":[{"internalType":"string","name":"id","type":"string"},{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"image","type":"string"},{"internalType":"string","name":"description","type":"string"}],"stateMutability":"view","type":"function","constant":true,"signature":"0x5a0908c0"},{"inputs":[],"name":"makeBid","outputs":[],"stateMutability":"payable","type":"function","payable":true,"signature":"0xf30e3658"},{"inputs":[],"name":"withdraw","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"pure","type":"function","constant":true,"signature":"0x3ccfd60b"}]'
);
const address = '0x2B07e85C59274EE6F4a463C45D2F86927C348341';

export default new web3.eth.Contract(abi, address);
